### ISSUE TITLE
Testing arStudio with a pattern Hiro

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/arStudio#23] opened 2020-02-21 17:31 UTC
### Basic Setup
I'm testing the basic functionality of arStudio, i started with the simplest scene:

- one **arComponent** with tackable detection set to trackable pattern and barcode (color).
- one **SceneNode**  with an **arTrackable2d** set to a Pattern (**Hiro**).
- a simple **Cube** with dimension 1.0 and position y = 0.5.

The scene file in .json format is here:

[simple_cube.zip](https://github.com/augmentmy-world/arStudio/files/4237228/simple_cube.zip)

## Testing instructions

Load the file locally, go to `Project > Load > From File`  then select your file and upload the file in the scene clicking the `Load File` button.
At this point select the player tab on the left of the editor and run the play button on the fight top of the editor.
My result with a **Hiro** pattern is this:

![Schermata da 2020-02-21 18-05-18](https://user-images.githubusercontent.com/1275858/75056586-a0298980-54d7-11ea-9039-95e43fffb905.png)

The cube should be perfectly sovraimposed on the **Hiro** marker  but it doesn't. It is shifted in the wrong axis, and when the Pattern is rotated the cube rotate in the wrong manner.

Maybe we use the wrong matrix or what? My setup is wrong?

**Comment by ThorstenBux** [comment] 2020-02-21 17:33
Position z=0.5 not y

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment] 2020-02-21 18:06
I tried also to change the other axis, the result was worst, but maybe the editor wasn't refreshing properly needs to try again. I would create some basic example so everybody can test.

**Comment by itamayo** [comment] 2020-03-11 11:16
You're doing a great job. I have tested it but seems is not display the cube,
https://drive.google.com/file/d/1jisOl36N5faSiYIEOwA4QCgw6ERw2WiI/view,

From logs, the application detects the marker but nothing is displaying:
```
warning: viewprojection matrix contains NaN when enableCamera is used
saw a trackable with id 0
```
EDIT:
If I change to scene view I can see how is affecting camera changes to cube position ...

**Comment by kalwalt** [comment] 2020-03-11 12:20
@itamayo we noted that it should be an issue with resizing (or related to) if you open the devTool what happens? or if you resize the window?

**Comment by itamayo** [comment] 2020-03-11 13:16
The console, not showing any error, only warnings about viewprojection matrix.
resize is not making any change, I saw that this.originalProjectionMatrix has NaN values, does can be the problem ? 
EDIT:
this.arCamera.getProjectionMatrix is return first value as NaN

**Comment by itamayo** [comment] 2020-03-11 13:25
Matrix get NaN after this line:
https://github.com/augmentmy-world/arStudio/blob/f456ea749f2ab5ba4bf420816f89b65e427ac884/editor/js/components/arcontroller.component.js#L289

**Comment by kalwalt** [comment] 2020-03-11 13:35
> The console, not showing any error, only warnings about viewprojection matrix.
> resize is not making any change, I saw that this.originalProjectionMatrix has NaN values, does can be the problem ?
> EDIT:
> this.arCamera.getProjectionMatrix is return first value as NaN

i had sometimes that error but the model showed. I says about the devConsol, try this now: with the editor open, open the devConsole, then load the example file and start the simulation.

**Comment by itamayo** [comment] 2020-03-11 13:52
Sorry but it isn't working, here a video. Seems that all process works (tracking) but not displaying
I have test with different resolution, with differente browser (firefox,chrome v80)
https://drive.google.com/file/d/1rRMPlIAPDjBOFW6VZb-hQspXY6ry9kqr/view?usp=sharing
EDIT : I'll tested on another user computer.

**Comment by kalwalt** [comment] 2020-03-11 14:02
@itamayo could be also that recent changes broke that example, as i'm bit busy (also for the upcoming v3.0.0 release of [AR.js](https://github.com/AR-js-org/AR.js) ) it's diffcult to say what's the problem now. If ihave a bit of time i will go back on this this late evening.

**Comment by itamayo** [comment] 2020-03-11 14:25
thanks, I tried different commits but  I didn't get working, I am little bit loss, thanks anyway and good luck with the AR.js 3v release ;)

**Comment by itamayo** [comment] 2020-03-11 15:29
The problem is in  this commit (commit before works!):
https://github.com/augmentmy-world/arStudio/commit/f456ea749f2ab5ba4bf420816f89b65e427ac884

There are some bugs using jquery ... 
Perhaps the best approach to rendering 3D content and video is to render video through 3D rendering, rather than rendering in html layers. To avoid resizing problems and so on...

**Comment by kalwalt** [comment] 2020-03-11 15:52
> The problem is in this commit (commit before works!):
> [f456ea7](https://github.com/augmentmy-world/arStudio/commit/f456ea749f2ab5ba4bf420816f89b65e427ac884)
> 
> There are some bugs using jquery ...

it could be, i will test again. Probably solved that issue but is sort out another, though looks strange to me. 

> Perhaps the best approach to rendering 3D content and video is to render video through 3D rendering, rather than rendering in html layers. To avoid resizing problems and so on...

Do you mean rendering in a separate window?

**Comment by itamayo** [comment] 2020-03-11 16:12
> Do you mean rendering in a separate window?

No, I mean render the video frame in the same canvas application is rendering the 3D content. rather than using video tag and canvas tag one over the other. I have done in another project, render video frame to virtual canvas, send this image to process to artoolkit, when tracking is hit, render video texutre plane + 3d objects. This way there is no need to adjust canvas tag and video tag since everything is the same 3d world.

**Comment by kalwalt** [comment] 2020-03-11 17:03
> No, I mean render the video frame in the same canvas application is rendering the 3D content. rather than using video tag and canvas tag one over the other. I have done in another project, render video frame to virtual canvas, send this image to process to artoolkit, when tracking is hit, render video texutre plane + 3d objects. This way there is no need to adjust canvas tag and video tag since everything is the same 3d world.

@itamayo we can discuss on it together with @ThorstenBux on a separate issue, I am open to any enhancement to the plugin.

**Comment by itamayo** [comment] 2020-03-12 09:00
ok ! thanks for your help ;)

**Comment by ThorstenBux** [comment] 2020-03-22 19:23
fixed with https://github.com/augmentmy-world/arStudio/pull/28 I think. Feel free to reopen

**Closed as completed by ThorstenBux** 2020-03-22 19:23 UTC
Labels: enhancement, good first issue, question
